ALTER TABLE users
ALTER COLUMN created_at
SET DEFAULT (NOW() AT TIME ZONE 'UTC');

ALTER TABLE users
ALTER COLUMN updated_at
SET DEFAULT (NOW() AT TIME ZONE 'UTC');

ALTER TABLE profiles
ALTER COLUMN created_at
SET DEFAULT (NOW() AT TIME ZONE 'UTC');

ALTER TABLE profiles
ALTER COLUMN updated_at
SET DEFAULT (NOW() AT TIME ZONE 'UTC');

