version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_service
    depends_on:
      - postgres
    command: [ "sh", "-c", "migrate -path /app/db/migrations -database postgres://postgres:postgres@postgres:5432/auth_service?sslmode=disable up && /auth-service" ]

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: